version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.12.7
    environment:
      GO111MODULE: "on"

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run:
          name: "Build binaries"
          command: |
            go build ./cmd/clog
            go build ./cmd/runsim
            go build ./cmd/slack
            go build ./cmd/github
            go build ./cmd/execmgmt

workflows:
  version: 2
  build-binaries:
    jobs:
      - build